name: Feature Request
description: Add or change gameplay behavior
title: "[Feature] "
labels:
  - feature
body:
  - type: textarea
    id: objective
    attributes:
      label: 目的
      description: 何を実現したいかを1-3行で書いてください。
      placeholder: 例) 画面タップでジャンプできるようにする
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: 受け入れ条件
      description: 確認可能な条件を箇条書きで書いてください。
      placeholder: |
        - タップでジャンプする
        - 二段ジャンプしない
        - ゲームオーバー中はジャンプしない
    validations:
      required: true

  - type: textarea
    id: out_of_scope
    attributes:
      label: 非対象
      description: 今回やらないことを書いてください。
      placeholder: 例) 効果音追加、エフェクト追加は今回対象外
    validations:
      required: false

  - type: textarea
    id: verify_steps
    attributes:
      label: 確認手順
      description: レビュアーが再現できる手順を書いてください。
      placeholder: |
        1. PagesプレビューURLを開く
        2. 画面をタップする
        3. 期待した挙動を確認する
    validations:
      required: true
